### ISSUE TITLE
The installation documentation is outdated and does not work anymore

### ISSUE THREAD

**Issue by Penta** [Penta/MyAnimeBot#2]
Hello, the installation documentation is outdated and should be reedited to take into account the Python 3.7 upgrade and the migration to GitHub which simplify the installation.

**Comment by LucasVilleneuve** [comment]
Now using requests package with the [AniList branch](https://github.com/Penta/MyAnimeBot/tree/AniList).
Please add it to the pip install requirements.

[requests package](https://pypi.org/project/requests/)

**Comment by Penta** [comment]
The installation procedure is now up to date.
You can find it [here](https://wiki.pentou.eu/en/project/myanimebot/install_rhel7).
